
# rstexocnpvtxfhqbnetn
[[functions]]
name = "zoho-config"
verify_jwt = true

[[functions]]
name = "zoho-tokens"
verify_jwt = false

[[functions]]
name = "zoho-transactions"
verify_jwt = true

[[functions]]
name = "stripe-balance"
verify_jwt = true

[[functions]]
name = "stripe-upcoming-payments"
verify_jwt = true

[[functions]]
name = "stripe-pending-activations"
verify_jwt = true

[[functions]]
name = "cache-manager"
verify_jwt = true

[[functions]]
name = "financial-assistant"
verify_jwt = true

[[functions]]
name = "exchange-rates"
verify_jwt = true

[[functions]]
name = "sync-client-status"
verify_jwt = false
